apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: banking-platform
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - banking

  selector:
    matchLabels:
      app.kubernetes.io/part-of: banking-platform

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
